### ISSUE TITLE
Directly feed ChemML with a RDKit molecule (object)

### ISSUE THREAD

**Issue by HenriqueCSJ** [hachmannlab/chemml#4]
Hello, thanks for the amazing code!
I'm working with a large pandas dataframe containing organometallic molecules in the **.mol V3000** format. RDKit can read it perfectly but as I can see ChemML, using the `Molecule` function, can read smiles, smarts, inchi, and xyz. For my molecules, I can't convert them to one line notations because that removes the correct geometry of the molecules, so, here is my question:

Since RDKit is reading the molecules correctly, is there a way to feed ChemML with the molecule objects already interpreted by RDKit?

**Comment by mojtabah** [comment]
Hi, thanks for your interest! As you mentioned, we don't support other formats yet. But, we plan to add them in the close future. 

Yes, you can override the rdkit molecule. Here is the workaround:

1. Let's say you can create a rdkit molecule with associated conformation. I am making one here:

`>>> from chemml.chem import Molecule`
`>>> m1 = Molecule('O', 'smiles') # water molecule`
`>>> m1.to_xyz(optimizer='UFF') # embed and optimize the 3D geometry`

This molecule gives you an rdkit molecule:
`>>> m1.rdkit_molecule`
`<rdkit.Chem.rdchem.Mol at 0x13b4b7d00>`
`>>> m1.xyz.geometry`
`array([[-6.62167743e-04,  4.04121065e-01,  0.00000000e+00],
       [-7.82704434e-01, -2.03343606e-01,  0.00000000e+00],
       [ 7.83366601e-01, -2.00777459e-01,  0.00000000e+00]])`

2. Based on what you described, you only have rdkit objects. Now, I want to create a new chemml molecule using that rdkit molecule only. You first need to instantiate the Molecule class using dummy info:

`>>> m2 = Molecule('C', 'smiles')`

Please note that if you try to create the xyz geometry with no optimization, the following error raises:

`>>> m2.to_xyz(optimizer=None)`
`ValueError: The conformation has not been built yet (maybe due to the 2D representation of the creator). You should set the optimizer value if you wish to embed and optimize the 3D geometry.`

Now, we replace its rdkit_molecule with the water molecule from the first step:

`>>> m2.rdkit_molecule = m1.rdkit_molecule # any rdkit.Chem.rdchem.Mol object` 

when you try to build the geometry with no optimizer, it gets the available conformation from your rdkit molecule:
`>>> m2.to_xyz(optimizer=None)`
`>>> m2.xyz.geometry`
`array([[-6.62167743e-04,  4.04121065e-01,  0.00000000e+00],
       [-7.82704434e-01, -2.03343606e-01,  0.00000000e+00],
       [ 7.83366601e-01, -2.00777459e-01,  0.00000000e+00]])`

`>>> m2`
`<chemml.chem.Molecule(`
`        rdkit_molecule : <rdkit.Chem.rdchem.Mol object at 0x13b5cdda0>,`
`       pybel_molecule : None,`
`        creator        : ('SMILES', 'C'),`
`       smiles         : 'C',`
`        smarts         : None,`
`        inchi          : None,`
`        xyz            : <XYZ(geometry: (3, 3), atomic_numbers: (3, 1), atomic_symbols: (3, 1))>)>`

You can also get the correct SMILES if you need:
`>>> m2.to_smiles()`
`>>> m2`
`<chemml.chem.Molecule(`
`        rdkit_molecule : <rdkit.Chem.rdchem.Mol object at 0x13b5cdda0>,`
`        pybel_molecule : None,`
`        creator        : ('SMILES', 'C'),`
`        smiles         : '[H]O[H]',`
`        smarts         : None,`
`        inchi          : None,`
 `       xyz            : <XYZ(geometry: (3, 3), atomic_numbers: (3, 1), atomic_symbols: (3, 1))>)>`

No worries about the creator, this is just the initial creator and as far as I remember doesn't make any issue. 

Please let me know if you have any other questions. Thanks!

**Comment by HenriqueCSJ** [comment]
Thanks, it worked like a charm!
